apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-persistent-volume-2
  namespace: playground-prince
spec: 
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: standard
  hostPath:
    path: /tmp/traefik-persistent-volume