apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: persistent-volume-claim-2
  namespace: playground-prince
spec: 
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: traefik-persistent-volume-2